// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Infra.DataContext;

namespace ProductsAPI.Infra.Migrations
{
    [DbContext(typeof(ProductsDataContext))]
    [Migration("20240320061426_migration-total-project")]
    partial class migrationtotalproject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnName("expirationdate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnName("manufacturingdate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierCode")
                        .HasColumnName("suppliercode")
                        .HasColumnType("INT");

                    b.HasKey("Code");

                    b.HasIndex("SupplierCode");

                    b.ToTable("product");
                });

            modelBuilder.Entity("ProductsAPI.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnName("cnpj")
                        .HasColumnType("NVARCHAR(14)");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Code");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("ProductsAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductsAPI.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
